---
title: "Willkommen zum Modul Computer Vision mit Deep Learning"
number-sections: false
---


Herzlich willkommen zum Modul **Computer Vision mit Deep Learning** (1. Teil)!

Hier finden Sie Unterlagen und aktuelle Informationen zum Modul.

[Modul Computer Vision mit DL](https://www.fhnw.ch/de/weiterbildung/informatik/fachvertiefungsmodule-data-science/computer-vision-mit-deep-learning)

[CAS Page](https://www.fhnw.ch/de/weiterbildung/informatik/cas-deep-learning)


## Lernziele

- Die fundamentalen Herausforderungen beim Modellieren von Bilddaten verstehen
- Convolutional Neural Networks verstehen, implementieren und trainieren können
- Foundation-Models als Grundlage für viele Vision Tasks verstehen und einsetzten können
- Bildklassifikation verstehen und systematisch umsetzen können
- Mit Deep Learning Frameworks umgehen und Libraries verwenden können
- Praktische Anwendung umsetzen, vorstellen und erklären können

## Inhalte

### Tag 1 -  Grundlagen CNNs und Bildklassifikation

| Zeit | Thema |
|------|--------|
|8:45 - 9:30	| Einführung Computer Vision mit Deep Learning
|9:30 - 10:30 	| Übung: Deep Learning mit PyTorch und Bildern
|10:30  - 10:45	| Pause
|10:45 - 12:00	| Convolutional Neural Networks
|12:00 - 13:00	| Mittagspause
|13:00 - 14:00	| Übung: CNNs vs MLPs
|14:15 - 15:00	| Theorie: Bildklassifikation
|15:15 - 16:30	| Übung: Bildklassifikation


### Tag 2 -  Foundation Models und Praktische Tipps

| Zeit | Thema |
|------|--------|
|8:45 - 10:00	| Theorie: Foundation Models & Representation Learning
|10:15 - 11:15 	| Übung: Foundation Models
|11:30  - 12:00	| Theorie: Praktische Tipps
|12:00 - 13:00	| Mittagspause
|13:00 - 15:30	| Übung: End-To-End Beispiel
|15:30  - 15:45	| Pause
|15:45  - 16:30	| Q&A / Buffer


<!--
| Datum | Thema                                               | Übung
|-----------------|-----------------------------------------------------|----------------------|
| 09 - 1.11.2024 | Einführung in Deep Learning für Computer Vision     | PyTorch Intro
| 10 - 2.11.2024 | Convolutional Neural Networks                       | Neural Networks / CNNs
           -->
